### PR TITLE
Addressed various errors, incompatibilities and their fixes.

### PR DESCRIPTION
**Pull request by SuchitReddi**
Updated README.md

Added comments to show if reload_data.py is running correctly.

Made a few more minor changes.

### CODE REVIEW

**Comment by yzyouzhang** [comment]
Thanks for your PR. Could you please ignore the __pycache__ and change the path?

**Comment by SuchitReddi** [comment]
Sorry, but I think I already deleted the **pycache** directory. Do you mean any other **pycache**? And what paths should I change? 
Thanks

**Comment by SuchitReddi** [comment]
I allowed edits by maintainers. Feel free to make the necessary changes you mentioned above, @yzyouzhang.

**Comment by SuchitReddi** [comment]
My apologies for any errors in this PR. Please let me know if there are any issues.

**Comment by yzyouzhang** [comment]
Thanks again for your PR. I'll take a look when I have time. It looks like there are many changes.

**Comment by SuchitReddi** [comment]
Sure, sorry for disturbing you! Take your time. By the way, there aren't major changes except in the README.md. The vast amount of lines is due to the cm_score file.

**Comment by SuchitReddi** [comment]
Unverified changes.

**Pull request closed without merging**
